import '../../models/leaderboard_model.dart';
import '../../models/recycling_point_model.dart';
import '../../models/reward_model.dart';
import '../../models/task_model.dart';
import '../../models/user_model.dart';
import '../../models/waste_log_model.dart';

class MockData {
  const MockData._();

  static final currentUser = UserModel(
    uid: 'mock_user_001',
    displayName: 'Ahmet',
    email: 'ahmet@example.com',
    photoUrl: null,
    totalPoints: 1240,
    weeklyPoints: 500,
    neighborhood: 'Yakutiye',
    schoolOrCampus: 'Atatürk Üniversitesi',
    badges: const ['ilk_atik', '1000_puan', 'kis_koruyucusu'],
    level: 7,
    createdAt: DateTime(2026, 1, 12),
    updatedAt: DateTime(2026, 1, 12),
  );

  static final tasks = <TaskModel>[
    const TaskModel(
      id: 'five_plastic',
      title: '5 Plastik Şişe',
      description: 'Bugün 5 plastik şişeyi doğru noktaya bırak.',
      type: TaskTypes.daily,
      pointReward: 50,
      requiredAction: TaskActions.scanPlastic,
      requiredCount: 5,
      isWinterOnly: false,
      iconEmoji: '🥤',
      currentCount: 3,
    ),
    const TaskModel(
      id: 'paper_collect',
      title: 'Atık Kağıt Topla',
      description: 'Kış boyunca kağıt atıklarını ayrı topla.',
      type: TaskTypes.winter,
      pointReward: 120,
      requiredAction: TaskActions.scanPaper,
      requiredCount: 10,
      isWinterOnly: true,
      iconEmoji: '📦',
      currentCount: 1,
    ),
    const TaskModel(
      id: 'battery_three',
      title: '3 Atık Pil',
      description: 'Atık pilleri güvenli pil toplama kutusuna bırak.',
      type: TaskTypes.daily,
      pointReward: 80,
      requiredAction: TaskActions.scanBattery,
      requiredCount: 3,
      isWinterOnly: false,
      iconEmoji: '🔋',
      currentCount: 0,
    ),
    const TaskModel(
      id: 'invite_friend',
      title: 'Arkadaşını Davet Et',
      description: 'Bir arkadaşını AtıkAvı Erzurum’a davet et.',
      type: TaskTypes.social,
      pointReward: 200,
      requiredAction: TaskActions.inviteFriend,
      requiredCount: null,
      isWinterOnly: false,
      iconEmoji: '🤝',
    ),
    const TaskModel(
      id: 'cup_lid',
      title: 'Karton bardak kapağını doğru kutuya at',
      description: 'Kafe atığını doğru ayrıştır ve kısa eğitimi tamamla.',
      type: TaskTypes.education,
      pointReward: 30,
      requiredAction: TaskActions.winterCupLid,
      requiredCount: 1,
      isWinterOnly: false,
      iconEmoji: '☕',
      currentCount: 1,
      isCompleted: true,
    ),
  ];

  static const rewards = <RewardModel>[
    RewardModel(
      id: 'cafe_discount_001',
      title: 'Sıfır Atık Kafe %10 İndirim',
      description: 'Anlaşmalı kafelerde kahve ve atıştırmalık indirimi.',
      requiredPoints: 250,
      category: RewardCategories.discount,
      sponsor: 'Sıfır Atık Kafe',
      iconEmoji: '☕',
      isActive: true,
      stockCount: 50,
    ),
    RewardModel(
      id: 'transport_001',
      title: 'Erzurum Kart Bakiye',
      description: 'Toplu taşıma için dijital bakiye kuponu.',
      requiredPoints: 700,
      category: RewardCategories.transport,
      sponsor: 'Erzurum Kart',
      iconEmoji: '🚌',
      isActive: true,
      stockCount: 20,
    ),
    RewardModel(
      id: 'tree_donation_001',
      title: 'Fidan Bağışı',
      description: 'Erzurum için senin adına bir fidan bağışı.',
      requiredPoints: 900,
      category: RewardCategories.donation,
      sponsor: 'AtıkAvı Erzurum',
      iconEmoji: '🌲',
      isActive: true,
      stockCount: 12,
    ),
    RewardModel(
      id: 'tea_coupon_001',
      title: 'Kahve / Çay Kuponu',
      description: 'Katılımcı işletmelerde sıcak içecek kuponu.',
      requiredPoints: 1500,
      category: RewardCategories.physical,
      sponsor: 'Yakutiye Esnaf Ağı',
      iconEmoji: '🫖',
      isActive: true,
      stockCount: 8,
    ),
    RewardModel(
      id: 'certificate_001',
      title: 'Geri Dönüşüm Elçisi Sertifikası',
      description: 'Profilinde görünecek dijital başarı sertifikası.',
      requiredPoints: 500,
      category: RewardCategories.certificate,
      sponsor: 'AtıkAvı Erzurum',
      iconEmoji: '🏅',
      isActive: true,
      stockCount: null,
    ),
  ];

  static const recyclingPoints = <RecyclingPointModel>[
    RecyclingPointModel(
      id: 'point_001',
      name: 'Yakutiye Geri Dönüşüm Merkezi',
      type: RecyclingPointTypes.plastic,
      latitude: 39.9056,
      longitude: 41.2658,
      address: 'Yakutiye, Erzurum merkez',
      qrCode: 'ATIKAVI_POINT_001',
      isActive: true,
      isBroken: false,
      workingHours: {'weekdays': '08:00-20:00', 'weekend': '10:00-18:00'},
    ),
    RecyclingPointModel(
      id: 'point_002',
      name: 'Atatürk Üniversitesi Kağıt Kutusu',
      type: RecyclingPointTypes.paper,
      latitude: 39.9069,
      longitude: 41.2372,
      address: 'Atatürk Üniversitesi Kampüsü, Erzurum',
      qrCode: 'ATIKAVI_POINT_002',
      isActive: true,
      isBroken: false,
      workingHours: {'weekdays': '09:00-18:00'},
    ),
    RecyclingPointModel(
      id: 'point_003',
      name: 'Havuzbaşı Pil Toplama',
      type: RecyclingPointTypes.battery,
      latitude: 39.9044,
      longitude: 41.2678,
      address: 'Havuzbaşı Kent Meydanı, Erzurum',
      qrCode: 'ATIKAVI_POINT_003',
      isActive: true,
      isBroken: false,
    ),
    RecyclingPointModel(
      id: 'point_004',
      name: 'Sıfır Atık Kafe',
      type: RecyclingPointTypes.cafe,
      latitude: 39.9088,
      longitude: 41.2762,
      address: 'Cumhuriyet Caddesi, Yakutiye',
      qrCode: 'ATIKAVI_POINT_004',
      isActive: true,
      isBroken: false,
      workingHours: {'weekdays': '08:00-22:00', 'weekend': '10:00-22:00'},
    ),
    RecyclingPointModel(
      id: 'point_005',
      name: 'Palandöken Cam Kumbarası',
      type: RecyclingPointTypes.glass,
      latitude: 39.8768,
      longitude: 41.2614,
      address: 'Palandöken, Erzurum',
      qrCode: 'ATIKAVI_POINT_005',
      isActive: true,
      isBroken: false,
      workingHours: {'weekdays': '08:00-19:00'},
    ),
    RecyclingPointModel(
      id: 'point_006',
      name: 'ETÜ Elektronik Atık Noktası',
      type: RecyclingPointTypes.electronic,
      latitude: 39.8958,
      longitude: 41.2454,
      address: 'Erzurum Teknik Üniversitesi Kampüsü',
      qrCode: 'ATIKAVI_POINT_006',
      isActive: true,
      isBroken: false,
      workingHours: {'weekdays': '09:00-18:00'},
    ),
    RecyclingPointModel(
      id: 'point_007',
      name: 'Şükrüpaşa Atık Yağ Noktası',
      type: RecyclingPointTypes.oil,
      latitude: 39.9218,
      longitude: 41.2752,
      address: 'Şükrüpaşa Mahallesi, Erzurum',
      qrCode: 'ATIKAVI_POINT_007',
      isActive: true,
      isBroken: false,
    ),
    RecyclingPointModel(
      id: 'point_008',
      name: 'Yıldızkent Plastik Noktası',
      type: RecyclingPointTypes.plastic,
      latitude: 39.8845,
      longitude: 41.2291,
      address: 'Yıldızkent Mahallesi, Palandöken',
      qrCode: 'ATIKAVI_POINT_008',
      isActive: true,
      isBroken: false,
    ),
  ];

  static const leaderboard = <LeaderboardModel>[
    LeaderboardModel(
      id: 'rank_001',
      category: LeaderboardCategories.individual,
      userId: 'user_001',
      name: 'Zeynep Kaya',
      weeklyPoints: 420,
      totalPoints: 1800,
      rank: 1,
      previousRank: 2,
    ),
    LeaderboardModel(
      id: 'rank_002',
      category: LeaderboardCategories.individual,
      userId: 'user_002',
      name: 'Mehmet Demir',
      weeklyPoints: 390,
      totalPoints: 1650,
      rank: 2,
      previousRank: 1,
    ),
    LeaderboardModel(
      id: 'rank_003',
      category: LeaderboardCategories.individual,
      userId: 'user_003',
      name: 'Elif Arslan',
      weeklyPoints: 360,
      totalPoints: 1510,
      rank: 3,
      previousRank: 4,
    ),
    LeaderboardModel(
      id: 'rank_004',
      category: LeaderboardCategories.individual,
      userId: 'mock_user_001',
      name: 'Ahmet',
      weeklyPoints: 350,
      totalPoints: 1240,
      rank: 124,
      previousRank: 130,
    ),
  ];

  static final wasteLogs = <WasteLogModel>[
    WasteLogModel(
      id: 'log_001',
      userId: currentUser.uid,
      wasteType: WasteTypes.plastic,
      verificationMethod: VerificationMethods.qr,
      qrPointId: 'point_001',
      latitude: 39.9056,
      longitude: 41.2658,
      pointsEarned: 10,
      loggedAt: DateTime(2026, 6, 1, 14, 30),
      status: WasteLogStatuses.approved,
    ),
    WasteLogModel(
      id: 'log_002',
      userId: currentUser.uid,
      wasteType: WasteTypes.paper,
      verificationMethod: VerificationMethods.photo,
      qrPointId: 'point_002',
      latitude: 39.9069,
      longitude: 41.2372,
      pointsEarned: 15,
      loggedAt: DateTime(2026, 6, 2, 10, 20),
      status: WasteLogStatuses.pending,
    ),
  ];
}
